spring:
  application:
    name: api-gateway-service

logging:
  level:
    root: info

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
      strip-prefix: true
      sensitive-headers: Cookie, Set-Cookie
      ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

ribbon:
  ReadTimeout: 3000