spring:
  application:
    name: api-gateway-service

logging:
  level:
    root: info

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
      strip-prefix: true
      sensitive-headers: Authorization
      ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
    data-service:
      path: /data/**
      service-id: data-service
      sensitive-headers: Authorization
    audit-service:
      path: /audit/**
      service-id: audit-service
      sensitive-headers: Authorization

ribbon:
  ReadTimeout: 3000