spring:
  application:
    name: auth-service
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/examble
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  activemq:
    broker-url: tcp://localhost:61616

logging:
  level:
    root: info

server:
  port: 9100

eureka:
  client:
    enabled: false
    service-url:
      default-zone: http://localhost:8761/eureka