spring:
  application:
    name: audit-service

logging:
  level:
    root: info

server:
  port: 9102

eureka:
  client:
#    enabled: false
    service-url:
      default-zone: http://localhost:8761/eureka